set my_design_name 					[getenv my_design_name]
set my_library_suffix 					[getenv my_library_suffix]
set my_tech_file 					[getenv my_tech_file]
set my_tcl_antenna_rule_file 				[getenv my_tcl_antenna_rule_file]
set my_tcl_user_redundant_via_mapping_file 		[getenv my_tcl_user_redundant_via_mapping_file]
set my_chip_finish_signal_em_constraint_format 		[getenv my_chip_finish_signal_em_constraint_format]
set my_chip_finish_signal_em_constraint_file 		[getenv my_chip_finish_signal_em_constraint_file]
set my_write_gds_layer_map_file 			[getenv my_write_gds_layer_map_file]
set my_reference_library_list 				[getenv my_reference_library_list]
set min_routing_layer 					[getenv min_routing_layer]
set max_routing_layer 					[getenv max_routing_layer]
set my_verilog_netlist_files 				[getenv my_verilog_netlist_files]
set my_def_scan_file 					[getenv my_def_scan_file]
set scan_def_flow					[getenv scan_def_flow]
set my_def_files 					[getenv my_def_files]
set my_upf_file 					[getenv my_upf_file]
set my_tcl_mcmm_setup_file 				[getenv my_tcl_mcmm_setup_file]
set my_tcl_parasitic_setup_file 			[getenv my_tcl_parasitic_setup_file]
set my_tcl_mv_setup_file 				[getenv my_tcl_mv_setup_file]
set my_placement_constraint_files 			[getenv my_placement_constraint_files]
set my_tcl_lib_cell_purpose_file 			[getenv my_tcl_lib_cell_purpose_file]
set my_tcl_pg_creation_file 				[getenv my_tcl_pg_creation_file]
set my_tcl_cts_ndr_rule_file 				[getenv my_tcl_cts_ndr_rule_file]
set my_tcl_tech_setup_file 				[getenv my_tcl_tech_setup_file]
set my_preroute_cts_primary_corner 			[getenv my_preroute_cts_primary_corner]
set my_place_opt_active_scenario_list 			[getenv my_place_opt_active_scenario_list]
set my_clock_opt_cts_active_scenario_list 		[getenv my_clock_opt_cts_active_scenario_list]
set my_route_opt_active_scenario_list 			[getenv my_route_opt_active_scenario_list]
set my_chip_finish_active_scenario_list 		[getenv my_chip_finish_active_scenario_list]
set my_icv_in_design_active_scenario_list 		[getenv my_icv_in_design_active_scenario_list]
set my_timing_eco_active_scenario_list 			[getenv my_timing_eco_active_scenario_list]
set my_route_focused_scenario 				[getenv my_route_focused_scenario]
set my_chip_finish_signal_em_scenario 			[getenv my_chip_finish_signal_em_scenario]
set my_chip_finish_metal_filler_prefix 			[getenv my_chip_finish_metal_filler_prefix]
set my_chip_finish_non_metal_filler_lib_cell_list	[getenv my_chip_finish_non_metal_filler_lib_cell_list]
set my_chip_finish_metal_filler_lib_cell_list 		[getenv my_chip_finish_metal_filler_lib_cell_list]
set my_chip_finish_signal_em_fixing 			[getenv my_chip_finish_signal_em_fixing]
set my_floorplan_file					[getenv my_floorplan_file]




